### ISSUE TITLE
Password is set  (RuntimeError) while running the container 

### ISSUE THREAD

**Issue by taragurung** [dismantl/onetimesecret-docker#2]
**Why exactly am I getting this error when running the container. Looks like some redis setting error. How can I fix it.** 

Generating OTS secret: 3826fac06a3d50ebe293b9ff0c08dd99f6383280
Generating Redis password: 7d8c4b8a5b5a502726b1a162cd9e0b95166b151c
/var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:47:in `call': ERR Client sent AUTH, but no password is set (RuntimeError)
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:24:in `connect'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:247:in `ensure_connected'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:137:in `block in process'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:206:in `logging'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:136:in `process'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:46:in `call'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis.rb:273:in `block in ping'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis.rb:18:in `synchronize'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis.rb:272:in `ping'
	from /var/lib/onetime/lib/onetime.rb:73:in `block in load!'
	from /var/lib/onetime/lib/onetime.rb:73:in `times'
	from /var/lib/onetime/lib/onetime.rb:73:in `load!'
	from config.ru:28:in `block in <main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>'

**Comment by Taytay** [comment]
First, thanks for doing the hard work of setting this up!

I too am getting this error.
I admit I haven't debugged yet. I will post back if I find anything!
```
$ docker run dismantl/onetimesecret
Generating OTS secret: b9779c099b3eb5f42301a4a46abde75cdc006906
Generating Redis password: 32ee6d534209b49a507e0f2f09e1ed659a931056
/var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:47:in `call': ERR Client sent AUTH, but no password is set (RuntimeError)
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:24:in `connect'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:247:in `ensure_connected'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:137:in `block in process'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:206:in `logging'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:136:in `process'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis/client.rb:46:in `call'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis.rb:273:in `block in ping'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis.rb:18:in `synchronize'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/redis-2.2.2/lib/redis.rb:272:in `ping'
	from /var/lib/onetime/lib/onetime.rb:73:in `block in load!'
	from /var/lib/onetime/lib/onetime.rb:73:in `times'
	from /var/lib/onetime/lib/onetime.rb:73:in `load!'
	from config.ru:28:in `block in <main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>'
```

**Comment by Taytay** [comment]
Ah, it appears to be because the Dockerfile is using the redis.conf from Onetimesecret (https://github.com/dismantl/onetimesecret-docker/blob/master/Dockerfile#L38), which comments out the password by default: https://github.com/onetimesecret/onetimesecret/blob/master/etc/redis.conf#L10

But the redis.conf file in this repo does not: https://github.com/dismantl/onetimesecret-docker/blob/master/redis.conf.example#L10

So it would appear that the intention is to use the ots.conf and redis.conf files from this repo, but that they are not actually used.

**Comment by dismantl** [comment]
Thanks for that @Taytay, indeed it was because of the password commenting. The latest commits should have solved this issue by modifying the `sed` command used by `entrypoint.sh`.
