### ISSUE TITLE
Creating Links always redirects to localhost

### ISSUE THREAD

**Issue by Exxou** [dismantl/onetimesecret-docker#8]
I've used the given docker-compose.yml but when I access the Website and create a Secret, the Link does not contain the Hostname. Instead it uses localhost. Is there a way to modify the container so the Website generates a accessable URL?

I've already modified the given .config file but that doesn't help either.

**Comment by sami-alajrami** [comment]
@Exxou how did you solve this?

**Comment by Exxou** [comment]
@sami-alajrami I realized that the container wasn't reading the config file because I didn't mount it properly. I mounted it in the docker-compose.yml and edited the given .config file as I needed it.
